"use strict";
require("dotenv").config();
const { getDb, getSetting } = require("../src/db");
getDb();
console.log("✅ Database initialised successfully.");
console.log("  Commission rate:", getSetting("commission_rate") + "%");
console.log("  Platform name:", getSetting("platform_name"));
console.log("  Currency:", getSetting("currency"));
console.log("\n🚀 Ready to start: npm start");
process.exit(0);
